"use client"

import { Brain } from "lucide-react"

interface HomeViewProps {
  t: any
  tasks: any[]
  onToggleTask: (id: number) => void
}

export function HomeView({ t, tasks, onToggleTask }: HomeViewProps) {
  return (
    <div className="relative h-full">
      <div className="grid gap-4 md:grid-cols-3 md:gap-6">
        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-sm transition hover:bg-slate-900/70">
          <h3 className="mb-1 text-sm font-semibold text-white">{t.statsTitle}</h3>
          <p className="mb-4 text-xs text-slate-400">{t.statsSubtitle}</p>
          <div className="mb-2 text-5xl font-bold text-white">82</div>
          <div className="inline-flex rounded-full bg-cyan-900/30 px-3 py-1 text-xs font-medium text-cyan-400 border border-cyan-800/50">
            {t.focusScoreLabel}
          </div>
          <div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800">
            <div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" style={{ width: "82%" }} />
          </div>
        </div>

        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-sm transition hover:bg-slate-900/70 md:col-span-2">
          <h3 className="mb-6 text-sm font-semibold text-white">{t.chartTitle}</h3>
          <div className="flex h-40 items-end gap-2">
            {[30, 45, 70, 60, 85, 55, 40].map((value, idx) => (
              <div key={idx} className="group flex flex-1 flex-col items-center gap-2">
                <div
                  className="w-full rounded-t-lg bg-gradient-to-t from-slate-700 to-cyan-900/50 transition-all duration-300 hover:scale-110 hover:from-cyan-400 hover:to-cyan-600 hover:shadow-lg hover:shadow-cyan-500/20"
                  style={{ height: `${value}%` }}
                />
                <span className="text-xs font-medium text-slate-500">{["M", "T", "W", "T", "F", "S", "S"][idx]}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-sm transition hover:bg-slate-900/70 md:col-span-2">
          <h3 className="mb-4 text-sm font-semibold text-white">{t.listTitle}</h3>
          {tasks.length === 0 ? (
            <p className="py-8 text-center text-sm text-slate-500">{t.listEmpty}</p>
          ) : (
            <ul className="space-y-3">
              {tasks.map((task) => (
                <li key={task.id} className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={task.completed}
                    onChange={() => onToggleTask(task.id)}
                    className="h-5 w-5 cursor-pointer rounded border-slate-600 bg-slate-800 text-cyan-500 transition focus:ring-2 focus:ring-cyan-500"
                  />
                  <span
                    className={`text-sm transition ${
                      task.completed ? "text-slate-500 line-through" : "text-slate-300"
                    }`}
                  >
                    {task.title}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-sm transition hover:bg-slate-900/70">
          <h3 className="mb-4 text-sm font-semibold text-white">{t.insightTitle}</h3>
          <div className="flex gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-purple-500 to-cyan-500 shadow-lg shadow-purple-500/20">
              <Brain className="h-5 w-5 text-white" />
            </div>
            <div className="flex-1 rounded-lg bg-white/5 p-3 border border-white/10">
              <p className="text-sm leading-relaxed text-slate-300">{t.insightText}</p>
            </div>
          </div>
          <div className="mt-3 text-xs text-slate-500">Generated by Lifenix AI</div>
        </div>
      </div>
    </div>
  )
}
